# Generated by Django 5.1 on 2024-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
